version: '3.8'

services:
  # OWASP Juice Shop - Intentionally vulnerable web application
  juice-shop:
    image: bkimminich/juice-shop:latest
    container_name: juice-shop
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=unsafe
    restart: unless-stopped

  # DVWA - Damn Vulnerable Web Application
  dvwa:
    image: vulnerables/web-dvwa:latest
    container_name: dvwa
    ports:
      - "8080:80"
    environment:
      - PHPIDS=off
    restart: unless-stopped
